"""A standard on-disk identity for an emem agent.

An agent that writes memory needs one ed25519 key, and it needs the SAME
key every session, because the key is what owns the agent's namespace at
`/memories/by_attester/<pubkey8>/...`. Lose it or change it and the agent
can no longer write where it wrote before. Until this module there was no
convention for where that key lives, so every caller invented its own,
which is exactly how two runs end up with two identities and a namespace
nobody owns twice.

The resolution order, first match wins:

1. `EMEM_AGENT_KEY` in the environment. Either a 64-character hex seed
   (used directly) or a path to a key file (PEM or hex).
2. The key file at `~/.emem/agent_ed25519.pem` (override the directory
   with `EMEM_HOME`). PKCS8 PEM, the format `openssl genpkey -algorithm
   ed25519` and the Rust responder both speak.
3. Nothing found: mint a fresh key, write it to that path with mode
   `0600`, and return it. `load_or_create_signer` does this;
   `load_signer` does not, so a caller that must not silently create an
   identity can tell the difference.

The key is a secret. It is written `0600`, never logged, and never
leaves the machine. Back it up the way you back up an SSH key: lose it
and you lose write access to everything the agent signed.
"""

from __future__ import annotations

import os
from pathlib import Path

from .signing import EmemSigner

#: Default key location. Overridable per file via `EMEM_AGENT_KEY`, or by
#: directory via `EMEM_HOME`.
DEFAULT_KEY_BASENAME = "agent_ed25519.pem"
ENV_KEY = "EMEM_AGENT_KEY"
ENV_HOME = "EMEM_HOME"


def default_key_path() -> Path:
    """`~/.emem/agent_ed25519.pem`, or `$EMEM_HOME/agent_ed25519.pem`."""
    home = os.environ.get(ENV_HOME)
    base = Path(home) if home else Path.home() / ".emem"
    return base / DEFAULT_KEY_BASENAME


def _looks_like_hex_seed(s: str) -> bool:
    s = s.strip()
    if len(s) != 64:
        return False
    try:
        bytes.fromhex(s)
    except ValueError:
        return False
    return True


def _signer_from_file(path: Path) -> EmemSigner:
    """Load a signer from a key file. Accepts PKCS8 PEM or a bare 64-char
    hex seed, so a key generated by `openssl` and one written by this
    module both load."""
    raw = path.read_bytes()
    text = raw.decode("ascii", errors="ignore").strip()
    if _looks_like_hex_seed(text):
        return EmemSigner.from_hex(text)
    # Otherwise treat it as PEM.
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    key = serialization.load_pem_private_key(raw, password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise ValueError(
            f"{path} is not an ed25519 private key "
            f"(got {type(key).__name__}); emem identities are ed25519"
        )
    seed = key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    return EmemSigner(seed)


def _resolve_from_env() -> EmemSigner | None:
    val = os.environ.get(ENV_KEY)
    if not val:
        return None
    val = val.strip()
    if _looks_like_hex_seed(val):
        return EmemSigner.from_hex(val)
    p = Path(val).expanduser()
    if not p.is_file():
        raise FileNotFoundError(
            f"{ENV_KEY} points at {p}, which is neither a 64-char hex seed "
            "nor an existing key file"
        )
    return _signer_from_file(p)


def load_signer(path: str | os.PathLike[str] | None = None) -> EmemSigner:
    """Load an existing identity. Raise if none is found.

    Checks `EMEM_AGENT_KEY` first (unless `path` is given explicitly),
    then the key file. Never creates a key: use this when a missing
    identity should be an error, not a silent new namespace.
    """
    if path is None:
        from_env = _resolve_from_env()
        if from_env is not None:
            return from_env
        key_path = default_key_path()
    else:
        key_path = Path(path).expanduser()
    if not key_path.is_file():
        raise FileNotFoundError(
            f"no emem identity at {key_path}. Set {ENV_KEY}, pass a path, or "
            "call load_or_create_signer() to mint one."
        )
    return _signer_from_file(key_path)


def _write_new_key(path: Path) -> EmemSigner:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    key = Ed25519PrivateKey.generate()
    pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    # Create 0600 from the start rather than write-then-chmod, so the key
    # is never briefly world-readable on disk.
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        os.write(fd, pem)
    finally:
        os.close(fd)
    seed = key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    return EmemSigner(seed)


def load_or_create_signer(
    path: str | os.PathLike[str] | None = None,
) -> EmemSigner:
    """Return a persistent identity, minting one on first use.

    Same resolution as `load_signer`, but when no key exists at the
    resolved file path it generates one, writes it `0600`, and returns
    it. An `EMEM_AGENT_KEY` that is set but unresolvable is still an
    error: an agent that was handed a key must not silently fall back to
    a different one.
    """
    if path is None:
        from_env = _resolve_from_env()
        if from_env is not None:
            return from_env
        key_path = default_key_path()
    else:
        key_path = Path(path).expanduser()
    if key_path.is_file():
        return _signer_from_file(key_path)
    return _write_new_key(key_path)
