#!/usr/bin/env python3
"""
emem Gemma-4 "explain" sidecar — an OPTIONAL, clearly-UNSIGNED natural-language
layer over emem's signed facts.

Why this exists
---------------
emem's /v1/ask synthesis is deliberately deterministic and LLM-free: the
`answer` string is a pure projection of the signed fact set, so the receipt is
byte-stable and re-verifiable offline. That property is non-negotiable and this
sidecar does NOT touch it.

This service is a separate process. It READS an emem /v1/ask response (the
signed facts + the deterministic answer) and asks Gemma-4-12B to phrase it for a
non-expert. The model never invents numbers — it only rewords the ones emem
already signed. The output is explicitly marked `signed: false`; the signed
artifact remains the emem receipt, not this prose. Nothing here writes a fact,
mints a CID, or signs anything.

Gemma-4 12B is the embedding-first VALIDATION emem cites (encoder-free, June
2026); here it is used purely as a reasoner over already-signed facts.

Run
---
    /home/ubuntu/memory-injection/.venv/bin/python explain_sidecar.py
    # GET  /health
    # POST /explain   {"ask": <emem /v1/ask response JSON>}  ->  {explanation, ...}

Env: EMEM_EXPLAIN_BIND (default 127.0.0.1:5071), EMEM_EXPLAIN_MODEL
(default google/gemma-4-12B-it), EMEM_EXPLAIN_MAX_TOKENS (default 160).
"""
import os, json, time, threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

MODEL = os.environ.get("EMEM_EXPLAIN_MODEL", "google/gemma-4-12B-it")
BIND = os.environ.get("EMEM_EXPLAIN_BIND", "127.0.0.1:5071")
MAX_TOKENS = int(os.environ.get("EMEM_EXPLAIN_MAX_TOKENS", "160"))

_tok = None
_model = None
_lock = threading.Lock()

SYSTEM = (
    "You explain emem's SIGNED Earth-observation facts to a non-expert. "
    "Rules: (1) be concise, 2-4 sentences; (2) interpret ONLY the numbers given "
    "— never invent or estimate a value; (3) if a reading is absent, say it is "
    "not measured rather than guessing; (4) do not claim this explanation is "
    "signed — the signed artifact is emem's receipt, this is plain commentary."
)


def _load():
    global _tok, _model
    if _model is not None:
        return
    with _lock:
        if _model is not None:
            return
        import torch
        from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
        t0 = time.time()
        bnb = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_quant_type="nf4",
        )
        _tok = AutoTokenizer.from_pretrained(MODEL)
        _model = AutoModelForCausalLM.from_pretrained(
            MODEL, quantization_config=bnb, device_map="cuda:0", torch_dtype=torch.bfloat16
        )
        print(f"[explain] loaded {MODEL} (4-bit) in {time.time()-t0:.0f}s", flush=True)


def _digest_ask(ask: dict) -> str:
    """Pull only the signed, factual surface of an emem /v1/ask response so the
    model rewords facts, not the whole envelope."""
    keep = {
        "place_resolved": ask.get("place_resolved"),
        "answer": ask.get("answer"),
        "band_observations_summary": ask.get("band_observations_summary"),
        "algorithm_outcomes_summary": ask.get("algorithm_outcomes_summary"),
        "caveats": ask.get("caveats"),
        "signed_fact_count": len(ask.get("fact_cids") or []),
        "routed_to": ask.get("routed_to"),
    }
    return json.dumps({k: v for k, v in keep.items() if v is not None}, ensure_ascii=False)


def explain(ask: dict) -> dict:
    import torch
    _load()
    facts = _digest_ask(ask)
    msgs = [{"role": "user", "content": SYSTEM + "\n\nSigned facts:\n" + facts}]
    inputs = _tok.apply_chat_template(
        msgs, add_generation_prompt=True, return_tensors="pt", return_dict=True
    ).to("cuda:0")
    n_in = inputs["input_ids"].shape[1]
    t0 = time.time()
    with torch.no_grad():
        out = _model.generate(**inputs, max_new_tokens=MAX_TOKENS, do_sample=False)
    text = _tok.decode(out[0][n_in:], skip_special_tokens=True).strip()
    return {
        "explanation": text,
        "signed": False,
        "disclaimer": "Generated by Gemma-4-12B from emem's already-signed facts. "
        "This prose is NOT signed and is not a fact — verify the emem receipt "
        "(fact_cids / signature) for the ground truth it rewords.",
        "model": MODEL,
        "source_routed_to": ask.get("routed_to"),
        "source_signed_fact_count": len(ask.get("fact_cids") or []),
        "latency_ms": round((time.time() - t0) * 1000),
    }


class H(BaseHTTPRequestHandler):
    def _send(self, code, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/health":
            self._send(200, {"ok": True, "model": MODEL, "loaded": _model is not None, "signed_output": False})
        else:
            self._send(404, {"error": "POST /explain or GET /health"})

    def do_POST(self):
        if self.path != "/explain":
            return self._send(404, {"error": "POST /explain"})
        try:
            n = int(self.headers.get("content-length", 0))
            req = json.loads(self.rfile.read(n) or b"{}")
            ask = req.get("ask") or req
            self._send(200, explain(ask))
        except Exception as e:  # noqa: BLE001
            self._send(500, {"error": str(e)})

    def log_message(self, *a):  # quiet
        pass


if __name__ == "__main__":
    host, port = BIND.split(":")
    print(f"[explain] loading model…", flush=True)
    _load()
    srv = ThreadingHTTPServer((host, int(port)), H)
    print(f"[explain] serving on http://{BIND}  (POST /explain, GET /health)", flush=True)
    srv.serve_forever()
