#!/usr/bin/env python3
"""The design system holds: one token file, one scale, and a dark mode on every page.

Why this exists
---------------
Every page in web/ used to carry its own copy of the token block. They drifted,
because a copy always does. /guard set --t-base to .84375rem, so its body copy
rendered at 13.5px while the homepage rendered at 16px, and neither page could
tell you which was intended. Three pages requested no webfont at all and drew
in whatever monospace the reader's system happened to pick.

Consolidating that was a one-time fix. This is what keeps it fixed, because the
next person to add a page will copy an existing one, and the copy is the whole
problem.

It also encodes a mistake made while consolidating. The migration removed each
page's dark-mode :root unconditionally. Six pages use a --bg/--fg token
namespace of their own rather than the shared --paper/--ink, so for those the
removal left no dark palette at all: /verify shipped a light body over a dark
--paper, and nothing caught it because the tokens themselves were fine. Check 4
is that bug written down.

What it checks
--------------
1. Every page links /tokens.css, and requests both families.
2. No page redefines a token the shared file already defines. A page may add a
   token of its own; it may not fork one.
3. No literal font-size anywhere. Sizes come from the scale or they are drift
   waiting to happen.
4. A page that defines its own colour namespace still has a dark-mode block.
   Removing one is how /verify broke.

Exit codes
----------
  0  the system holds
  1  a page forked a token, hardcoded a size, or lost its dark mode
  2  could not run

Usage
-----
  python3 scripts/design_tokens.py
"""

from __future__ import annotations

import glob
import os
import re
import sys

TOKENS = "web/tokens.css"

# The tokens no page may fork. Type scale, spacing ladder, the ratio
# itself, and the two families. Colour is not here on purpose.
SCALE_TOKENS = frozenset(
    [f"--t-{k}" for k in ("3xs", "2xs", "xs", "sm", "base", "md", "lg",
                          "xl", "2xl", "3xl", "4xl", "5xl", "6xl")]
    + [f"--s-{i}" for i in range(1, 9)]
    + ["--phi", "--mono", "--display"])

# Pages that are not part of the site's visual system. Each needs a reason.
EXEMPT = {
    "channel.html": "generated by scripts/build_channel.py; its styling is "
                    "regenerated from the ledger, not hand-maintained",
}


def main():
    try:
        shared = open(TOKENS, encoding="utf-8").read()
    except OSError as e:
        print(f"design-tokens: cannot read {TOKENS}: {e}", file=sys.stderr)
        return 2

    shared_names = set(re.findall(r'(--[\w-]+)\s*:', shared))
    if not shared_names:
        print(f"design-tokens: {TOKENS} defines no tokens, so this gate is "
              f"measuring nothing.", file=sys.stderr)
        return 2

    pages = sorted(glob.glob("web/*.html"))
    if not pages:
        print("design-tokens: no pages found", file=sys.stderr)
        return 2

    fails = []
    checked = 0

    for path in pages:
        name = os.path.basename(path)
        if name in EXEMPT:
            continue
        checked += 1
        s = open(path, encoding="utf-8").read()

        if "/tokens.css" not in s:
            fails.append(f"{name} does not link /tokens.css, so it carries its "
                         f"own scale and will drift from every other page.")
        if "Newsreader" not in s:
            fails.append(f"{name} does not request the display face. Three pages "
                         f"requested no webfont at all and drew in whatever "
                         f"monospace the reader's system picked.")

        # A page may not fork the SCALE. Colour is deliberately not covered:
        # /gallery, /scoreboard and /tools carry palettes of their own on
        # purpose, and a dark-mode :root legitimately restates every colour.
        # The scale is different. It is the thing that drifted, and there is no
        # honest reason for one page to disagree with another about how big
        # body copy is. /404 was still setting --t-xs to 11px and --t-lg to
        # 22px, which is the small-type complaint in its original form.
        for block in re.findall(r':root\s*\{(.*?)\}', s, re.S):
            for tok in re.findall(r'(--[\w-]+)\s*:', block):
                if tok in SCALE_TOKENS and tok in shared_names:
                    fails.append(
                        f"{name} redefines {tok}. The scale lives in "
                        f"/tokens.css; a page that disagrees with it about how "
                        f"big body copy is has re-created the original bug.")

        for m in re.finditer(r'font-size:\s*([0-9.]+(?:rem|px))(?=[;}\s])', s):
            fails.append(f"{name} sets font-size:{m.group(1)} literally. "
                         f"Sizes come from the scale.")

        # Check 4. A page with its own colour namespace owns its own dark mode.
        own_namespace = bool(re.search(r':root\s*\{[^}]*--(?:bg|fg)\s*:', s, re.S))
        has_dark = bool(re.search(r'@media[^{]*prefers-color-scheme:\s*dark', s))
        if own_namespace and not has_dark:
            fails.append(
                f"{name} defines its own --bg/--fg palette and has no "
                f"dark-mode block. The shared file defines --paper/--ink, "
                f"which this page never reads, so dark mode does not reach it.")

    print(f"design tokens: {checked} pages checked against {len(shared_names)} "
          f"shared tokens, {len(EXEMPT)} exempt")

    if fails:
        print("\nThe next page will be a copy of an existing one. That is the "
              "whole problem.")
        seen = set()
        for f in fails:
            if f in seen:
                continue
            seen.add(f)
            print(f"  {f}")
        return 1
    print("One token file, one scale, and every page has a dark mode.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
