#!/usr/bin/env python3
"""Generate and validate the ChatGPT submission bundle against the live server.

Why
---
integrations/chatgpt/tools.md documented FOUR tools that do not exist:
`emem_ask_place`, `emem_locate_place`, `emem_recall_facts`, `emem_get_receipt`.
The submission JSON beside it declares nine real ones. A reviewer reading the
two files together would have found the app describing a surface the server
does not serve, and the example CIDs were `bafy...`, which is IPFS's format and
not ours.

Nothing in the bundle was generated, so nothing kept it honest. tools.md is
generated now, from the tool catalogue the responder actually serves, for
exactly the nine tools the submission declares. The rest of the bundle is
prose and stays hand-written, but the FACTS in it are checked here.

Checks (all of them fail loudly rather than warning):
  - every tool the submission declares exists in the live catalogue
  - its readOnlyHint / destructiveHint / openWorldHint match the live server
  - no justification contradicts the flag it justifies
  - the contact address matches the agent card
  - the tool count in the prose matches the live count

Usage:
  python3 scripts/gen_chatgpt_bundle.py
  python3 scripts/gen_chatgpt_bundle.py --check
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import urllib.request

REPO = pathlib.Path(__file__).resolve().parent.parent
BUNDLE = REPO / "integrations" / "chatgpt"
SUBMISSION = BUNDLE / "chatgpt-app-submission.json"
TOOLS_MD = BUNDLE / "tools.md"


def rpc(url: str, method: str, params: dict) -> dict:
    req = urllib.request.Request(
        url, data=json.dumps({"jsonrpc": "2.0", "id": 1,
                              "method": method, "params": params}).encode(),
        headers={"content-type": "application/json",
                 "accept": "application/json, text/event-stream"})
    raw = urllib.request.urlopen(req, timeout=90).read().decode()
    if raw.lstrip().startswith("data:"):
        raw = "\n".join(l[5:].strip() for l in raw.splitlines() if l.startswith("data:"))
    return json.loads(raw)["result"]


def catalogue(origin: str) -> dict:
    """Every tool the responder serves. /mcp advertises the core tier only, so
    this reads /mcp/full and follows nextCursor: reading one page and calling it
    the catalogue is how a tool comes to look absent when it is merely later."""
    out, cursor, pages = {}, None, 0
    while True:
        r = rpc(origin.rstrip("/") + "/mcp/full", "tools/list",
                {} if not cursor else {"cursor": cursor})
        for t in r["tools"]:
            out[t["name"]] = t
        cursor = r.get("nextCursor")
        pages += 1
        if not cursor or pages > 20:
            break
    return out


def check(sub: dict, live: dict, card: dict) -> list[str]:
    bad = []
    for name, decl in sub["tools"].items():
        t = live.get(name)
        if not t:
            bad.append(f"{name}: declared in the submission, not served by the responder")
            continue
        ann = t.get("annotations") or {}
        for flag in ("readOnlyHint", "destructiveHint", "openWorldHint"):
            if flag in decl and flag in ann and decl[flag] != ann[flag]:
                bad.append(f"{name}: declares {flag}={decl[flag]}, server says {ann[flag]}")
        # a justification that contradicts the flag beside it
        for flag in ("readOnlyHint", "destructiveHint", "openWorldHint"):
            for j in (decl.get(f"{flag}_justification"), ):
                if not j:
                    continue
                for other in ("readOnlyHint", "destructiveHint"):
                    m = re.search(rf"{other} is (true|false)", j)
                    if m and decl.get(other) is not (m.group(1) == "true"):
                        bad.append(f"{name}: {flag}_justification says "
                                   f"'{other} is {m.group(1)}' but {other} is {decl.get(other)}")
    contact = (card.get("emem") or {}).get("contact")
    for f in sorted(BUNDLE.glob("*.md")):
        text = f.read_text(encoding="utf-8")
        for addr in set(re.findall(r"[\w.+-]+@[\w.-]+\.\w+", text)):
            if contact and addr != contact:
                bad.append(f"{f.name}: contact {addr} does not match the agent card ({contact})")
    return bad


def render(sub: dict, live: dict, origin: str) -> str:
    lines = [
        "# Tools",
        "",
        "<!-- GENERATED by scripts/gen_chatgpt_bundle.py from the tool catalogue this",
        "     responder actually serves. Do not edit by hand: run the script.",
        "",
        "     This file previously documented four tools that do not exist",
        "     (emem_ask_place, emem_locate_place, emem_recall_facts, emem_get_receipt)",
        "     while the submission JSON beside it declared nine real ones. Nothing",
        "     generated it, so nothing kept it true. -->",
        "",
        f"The app declares **{len(sub['tools'])} tools**. Each one below is checked against "
        f"`{origin}/mcp/full` at generation time: the name exists, and the MCP annotations "
        "here are the annotations the server sends.",
        "",
        "Reads need no key and no account. None of emem's write verbs is exposed in this app.",
        "",
    ]
    for name in sub["tools"]:
        t = live[name]
        decl = sub["tools"][name]
        ann = t.get("annotations") or {}
        schema = t.get("inputSchema") or {}
        props = schema.get("properties") or {}
        required = schema.get("required") or []
        desc = " ".join((t.get("description") or "").split())
        if len(desc) > 600:
            desc = desc[:597].rsplit(" ", 1)[0] + "…"
        lines += [f"## `{name}`", "", desc, ""]
        ro = ann.get("readOnlyHint")
        lines += [
            f"**Read-only:** {'yes' if ro else 'no'}. "
            + (" ".join((decl.get("readOnlyHint_justification") or "").split())[:400]
               if not ro else "It reads and returns; it adds nothing another reader would see."),
            "",
        ]
        if props:
            # Required keys first: the first version listed six optional fields
            # and omitted the one required field directly above a line saying it
            # was required, which is a worked example that does not work.
            order = [k for k in required if k in props] + \
                    [k for k in props if k not in required]
            body = []
            for k in order[:7]:
                spec = props[k] or {}
                ex = spec.get("example")
                if ex is None:
                    ex = {"string": f"<{k}>", "number": 0, "integer": 0,
                          "boolean": False, "array": [], "object": {}}.get(spec.get("type"), f"<{k}>")
                # ensure_ascii=False, or a placeholder renders as \u2026 in a code block
                body.append((k, json.dumps(ex, ensure_ascii=False), k in required))
            width = max(len(json.dumps(k, ensure_ascii=False)) + len(v) for k, v, _ in body)
            rows = []
            for i, (k, v, req) in enumerate(body):
                pair = f'{json.dumps(k, ensure_ascii=False)}: {v}'
                comma = "," if i < len(body) - 1 else ""
                note = "" if req else f'{" " * max(1, width + 2 - len(pair) - len(comma))}// optional'
                rows.append(f"  {pair}{comma}{note}")
            lines += ["**Input**", "", "```json", "{"] + rows + ["}", "```", ""]
            if required:
                lines += ["Required: " + ", ".join(f"`{r}`" for r in required), ""]
        lines += ["---", ""]
    lines += [
        "## Verifying any answer",
        "",
        "Every response carries an ed25519 receipt. `emem_verify_receipt` checks it against "
        f"the responder's published key at `{origin}/.well-known/emem.json`, so an answer can "
        "be checked without trusting the responder that produced it. Fact identifiers are "
        "base32 blake3 content addresses over canonical CBOR; they are not IPFS CIDs and do "
        "not begin with `bafy`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--origin", default="https://emem.dev")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    sub = json.loads(SUBMISSION.read_text(encoding="utf-8"))
    try:
        live = catalogue(a.origin)
        card = json.loads(urllib.request.urlopen(
            a.origin.rstrip("/") + "/.well-known/agent-card.json", timeout=45).read().decode())
    except Exception as e:
        print(f"could not read the responder at {a.origin}: {type(e).__name__}: {e}")
        print("Undetermined, not clean: this bundle is validated AGAINST the server,")
        print("so an unreachable server means nothing here was checked.")
        return 2

    problems = check(sub, live, card)
    if problems:
        print(f"the submission bundle disagrees with {a.origin}:")
        for p in problems:
            print("  ", p)
        return 1

    body = render(sub, live, a.origin)
    if a.check:
        if not TOOLS_MD.exists() or TOOLS_MD.read_text(encoding="utf-8") != body:
            print("integrations/chatgpt/tools.md is stale; run scripts/gen_chatgpt_bundle.py")
            return 1
        print(f"bundle agrees with {a.origin}: {len(sub['tools'])} tools declared, all served, "
              f"annotations match, no contradictory justifications, contact matches the card")
        print(f"  scope: the {len(sub['tools'])} tools this submission DECLARES, checked against")
        print(f"  the live catalogue, plus tools.md and the e-mail addresses in "
              f"{len(list(BUNDLE.glob('*.md')))} .md file(s).")
        print("  NOT covered: whether the prose is accurate, whether the declared set")
        print("  is the right set, and the domain-verification token, which the portal")
        print("  reissues per submission and no check here can know.")
        return 0
    TOOLS_MD.write_text(body, encoding="utf-8")
    print(f"wrote {TOOLS_MD.relative_to(REPO)} from {len(live)} live tools "
          f"({len(sub['tools'])} declared)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
