#!/usr/bin/env python3
"""The first thirty lines of the agent guide, generated from the intent registry.

Why this exists
---------------
`docs/agents.md` opens with what emem IS. That is the right second thing and
the wrong first thing. An agent arriving with a problem has to read twenty
lines of positioning before it learns whether to keep reading, and the tool
names it needs are a thousand lines further down.

So the guide now opens with a decision layer: use it when, do NOT use it when,
first call, and a need-to-tool table. Nothing here is new capability. It is the
same registry the responder serves at `/v1/intents`, arranged so the decision
can be made in one screen.

Why it is generated rather than written
---------------------------------------
Because a hand-written summary of a machine-readable table is a paraphrase, and
this project exists to argue against paraphrase. The failure would be the
ordinary one: someone adds an intent to the Rust table, the header keeps its
old list, and an agent reading the guide routes on a map that stopped matching
the responder. There is no way to notice that by reading either file alone.

The rule the block obeys, and the reason the DO NOT list is not optional: a
row the registry marks `not_served` appears under DO NOT USE with its reason.
An index that lists only strengths makes the caller discover the limits after
committing, which is a worse outcome than not being found.

    python3 scripts/gen_decision_layer.py --check   # CI: fails on drift
    python3 scripts/gen_decision_layer.py --write   # regenerate in place

Exit codes: 0 in step, 1 drifted (or written), 2 could not run.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUIDE = os.path.join(REPO, "docs/agents.md")
START = "<!-- decision-layer:start (generated by scripts/gen_decision_layer.py) -->"
END = "<!-- decision-layer:end -->"
DEFAULT_ORIGIN = os.environ.get("EMEM_ORIGIN", "https://emem.dev")


def fetch(origin):
    req = urllib.request.Request(origin.rstrip("/") + "/v1/intents",
                                 headers={"accept": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read())


def terse(row):
    """The scannable form of a row: the label the registry chose.

    An earlier version picked the shortest alias and produced "persistent
    Earth state" and a bare "provenance" as headlines, which is unclear and
    is the geo-first framing the registry exists to correct. Length is not a
    proxy for clarity, so the label is now content in the table itself and
    this only reads it.
    """
    s = row.get("short")
    if s:
        return s
    s = row.get("need", "")
    for pre in ("I need to ", "I need "):
        if s.startswith(pre):
            s = s[len(pre):]
            break
    return s[:1].upper() + s[1:] if s else row.get("need", "")


def render(reg):
    rows = reg.get("intents", [])
    served = [r for r in rows if r.get("coverage") == "served"]
    partial = [r for r in rows if r.get("coverage") == "partial"]
    unserved = [r for r in rows if r.get("coverage") == "not_served"]

    out = [START, "", "## Decide in one screen", "",
           "*Generated from [`/v1/intents`](https://emem.dev/v1/intents). "
           "Do not edit by hand; run `scripts/gen_decision_layer.py --write`.*",
           "", "**USE emem WHEN**", ""]
    for r in served:
        out.append(f"- {terse(r)}")
    out += ["", "**DO NOT USE emem WHEN**", ""]
    for r in unserved:
        # The reason is the useful half. "Not supported" strands the caller;
        # naming the missing mechanism lets it decide what to do instead.
        why = r.get("why", "").split(".")[0].strip()
        out.append(f"- **{terse(r)}.** {why}. "
                   f"Instead: {r.get('instead','').split('.')[0].strip()}.")
    if partial:
        out += ["", "**PARTLY**", ""]
        for r in partial:
            why = r.get("why", "").split(".")[0].strip()
            out.append(f"- **{terse(r)}.** {why}.")

    out += ["", "**FIRST CALL**", "",
            "```", "emem_tools            # the catalogue, when you do not know the primitive",
            "emem_recall           # facts at a place, signed, with a receipt",
            "```", "",
            "**IF YOU NEED**", "",
            "| you need | call |", "|---|---|"]
    for r in served:
        tool = r.get("tool") or ""
        if not tool:
            continue
        out.append(f"| {terse(r)} | `{tool}` |")

    out += ["", "**MCP**  `https://emem.dev/mcp` (16-tool core loop) · "
            "`https://emem.dev/mcp/full` (everything)", "",
            "**READS NEED NO KEY.** No account, no token, no bearer. A key is "
            "required only to WRITE, because a signature the responder could "
            "produce for you would attest nothing about you.", "",
            "**VERIFY, DO NOT TRUST.** Every read carries an ed25519 receipt. "
            "Check it with `emem_verify_receipt`, or offline at "
            "[/verify](https://emem.dev/verify). A read you did not verify is "
            "hearsay, including one from us.", "", END]
    block = "\n".join(out)
    # The house prose convention bans em and en dashes, and doc_lint enforces
    # it. A generator is precisely where a banned character comes back without
    # anyone deciding to reintroduce it, so refuse here rather than emit a
    # block that fails the lint after it has been written to the guide.
    for bad in ("\u2014", "\u2013"):
        assert bad not in block, (
            "the generated decision layer contains a dash the prose convention "
            "bans; fix the template, not docs/agents.md"
        )
    return block


def splice(text, block):
    if START in text and END in text:
        a = text.index(START)
        b = text.index(END) + len(END)
        return text[:a] + block + text[b:]
    # First run: insert after the H1 and its tagline.
    lines = text.split("\n")
    for i, l in enumerate(lines):
        if l.startswith("# "):
            j = i + 1
            while j < len(lines) and (not lines[j].strip() or lines[j].startswith("*")):
                j += 1
            return "\n".join(lines[:j]) + "\n" + block + "\n\n" + "\n".join(lines[j:])
    return block + "\n\n" + text


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--origin", default=DEFAULT_ORIGIN)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()

    try:
        reg = fetch(a.origin)
    except Exception as e:
        print(f"decision-layer: could not read {a.origin}/v1/intents ({e}); "
              f"nothing asserted.", file=sys.stderr)
        return 2
    rows = reg.get("intents", [])
    if not rows:
        print("decision-layer: the registry came back empty, so this would "
              "generate a header claiming emem does nothing.", file=sys.stderr)
        return 2

    block = render(reg)
    text = open(GUIDE, encoding="utf-8").read()
    updated = splice(text, block)

    if a.write:
        open(GUIDE, "w", encoding="utf-8").write(updated)
        print(f"decision-layer: written, {len(rows)} intents "
              f"({sum(1 for r in rows if r.get('coverage') == 'served')} served)")
        return 0

    if updated != text:
        print("decision-layer: docs/agents.md disagrees with the responder's "
              "intent registry. The guide's first screen is what an agent "
              "routes on, so a stale one sends it to a tool for a need we no "
              "longer serve, or hides one we do.")
        print("  run: python3 scripts/gen_decision_layer.py --write")
        if os.environ.get("GITHUB_ACTIONS") == "true":
            print("::error title=decision-layer::docs/agents.md decision layer "
                  "is out of step with /v1/intents")
        return 1
    print(f"decision-layer: in step with the registry ({len(rows)} intents)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
