#!/usr/bin/env python3
"""One 'Listed on' column, in every footer, from one definition.

The nav had seven shapes across twenty-two pages before gen_nav.py; the footer
still has seven across seventeen. This does not rewrite those seven -- each
carries links that page has a reason for -- it adds the ONE column that has to
say the same thing everywhere, and it owns that column so the next destination
is added in one place rather than in seventeen.

The list is imported from gen_nav.PORTS, so the bar and the footer cannot come
to disagree about where emem is listed. That is the whole reason this is a
script and not a paste.

Usage:
  python3 scripts/gen_footer_ports.py            # insert or refresh
  python3 scripts/gen_footer_ports.py --check    # report drift, write nothing
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
from gen_nav import PORTS  # noqa: E402  the single definition

START = "<!--ports:start-->"
END = "<!--ports:end-->"
# Where emem is listed, plus the two that are about the work rather than the
# distribution. These are footer-only on purpose: four in the bar is the limit
# before it becomes a second navigation.
EXTRA = [
    ("Glama", "https://glama.ai/mcp/servers/Vortx-AI/emem", "MCP server directory"),
    ("MCP Toplist", "https://mcptoplist.com/server/io.github.Vortx-AI%2Femem", "MCP server directory"),
    ("Zenodo", "https://doi.org/10.5281/zenodo.20706893", "the whitepaper, with a DOI"),
]

FOOTER = re.compile(r'(<footer class="page foot[^"]*">.*?</footer>)', re.S)
BLOCK = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)


def column() -> str:
    rows = "\n".join(
        f'          <li><a href="{href}" rel="noopener" title="{note}">{label}</a></li>'
        for label, href, note in list(PORTS) + EXTRA)
    return (f"{START}\n"
            "      <!-- Generated by scripts/gen_footer_ports.py from gen_nav.PORTS.\n"
            "           Do not edit by hand: the bar and the footer read one list, so\n"
            "           that they cannot come to disagree about where emem is listed. -->\n"
            '      <div class="foot-col">\n'
            "        <h4>Listed on</h4>\n"
            "        <ul>\n"
            f"{rows}\n"
            "        </ul>\n"
            "      </div>\n"
            f"      {END}")


# The column count was hard-coded per page: repeat(4,1fr) on some, repeat(5,1fr)
# on others. Adding a column to a fixed grid wraps it onto a second row on its
# own, which is what made the footer stop looking deliberate. auto-fit sizes to
# whatever columns are actually there, so the next addition does not need a
# second edit in seventeen files.
GRID = re.compile(r'\.foot-grid\{display:grid;grid-template-columns:repeat\(\d+,1fr\);gap:([^}]*)\}')


def widen_grid(html: str) -> str:
    return GRID.sub(
        lambda m: (".foot-grid{display:grid;"
                   "grid-template-columns:repeat(auto-fit,minmax(9.5rem,1fr));"
                   f"gap:{m.group(1)}}}"),
        html)


def apply(html: str) -> str | None:
    """Return the updated page, or None when there is nothing to do."""
    html = widen_grid(html)
    m = FOOTER.search(html)
    if not m:
        return None
    foot = m.group(1)
    col = column()
    if BLOCK.search(foot):
        new_foot = BLOCK.sub(lambda _: col, foot)
    else:
        # after the LAST foot-col, so it reads as the final column
        last = foot.rfind("</div>", 0, foot.rfind("</div>", 0, foot.rfind("</div>")))
        anchor = foot.rfind('<div class="foot-col">')
        if anchor == -1:
            return None
        close = foot.find("</div>", foot.find("</ul>", anchor))
        if close == -1:
            return None
        cut = close + len("</div>")
        new_foot = foot[:cut] + "\n" + col + foot[cut:]
    out = html[:m.start(1)] + new_foot + html[m.end(1):]
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    changed, skipped = [], []
    for path in sorted((REPO / "web").glob("*.html")):
        html = path.read_text(encoding="utf-8")
        out = apply(html)
        if out == html:
            continue
        if out is None:
            if FOOTER.search(html) is None:
                skipped.append(path.name)
            continue
        changed.append(path.name)
        if not a.check:
            path.write_text(out, encoding="utf-8")
    total = len([p for p in (REPO / "web").glob("*.html")
                 if FOOTER.search(p.read_text(encoding="utf-8"))])
    if a.check:
        if changed:
            print(f"'Listed on' is missing or stale in {len(changed)} of {total} footers:")
            for c in changed:
                print("  ", c)
            print("Run: python3 scripts/gen_footer_ports.py")
            return 1
        nofoot = len([p for p in (REPO / "web").glob("*.html")
                      if not FOOTER.search(p.read_text(encoding="utf-8"))])
        print(f"every one of {total} footers carries the same 'Listed on' column "
              f"({len(PORTS) + len(EXTRA)} destinations)")
        print(f"  scope: web/*.html only. {nofoot} page(s) carry no footer at all and")
        print("  are not examined; a page that loses its footer would leave this")
        print("  line unchanged and drop out of the denominator.")
        return 0
    print(f"{len(changed)} of {total} footers updated "
          f"({len(PORTS) + len(EXTRA)} destinations); "
          f"{len(skipped)} page(s) carry no footer")
    for c in changed:
        print("  ", c)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
