#!/usr/bin/env python3
"""One navigation, generated into every page from one definition.

Why this exists
---------------
The site had SEVEN different navigation bars across 22 pages, and between them
they reached 13 of 142 human-facing routes. Which pages you could get to
depended on which page you were standing on. The homepage's nav was unique and
linked to none of /how-it-works, /solutions, /reference, /demos, /a2a, /verify
or /docs. The main variant, on 16 pages, linked to none of /guard, /worlds,
/tools, /channel, /scoreboard, /gallery or /whitepaper. /guard appeared in
exactly one nav: its own.

That is what happens when a nav is copied. So it is generated now, and a gate
compares every page against this file.

Shape
-----
Four groups, named for what a reader wants to do rather than for how the
project is organised, because the reader does not know how the project is
organised. Each group is a <details> element: it opens on click and on Enter,
it is reachable by keyboard, and it works with JavaScript disabled. No script
runs for the navigation at all.

Editing
-------
Add a destination to NAV below and run this. Never edit the nav in a page: the
gate regenerates and compares, so a hand edit is reported as drift.

Usage
-----
  python3 scripts/gen_nav.py --check      report drift, write nothing
  python3 scripts/gen_nav.py              rewrite every page's nav
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import sys

START = "<!--nav:start-->"
END = "<!--nav:end-->"

# label, href, one-line note shown under the label.
NAV = [
    ("Understand", [
        ("How it works", "/how-it-works", "the address, the fact, the receipt"),
        ("Solutions", "/solutions", "four agents already running on it"),
        ("Whitepaper", "/whitepaper", "the long form, with the proofs"),
        ("The spec", "/spec", "wire format, preimages, canonical bytes"),
    ]),
    ("See it run", [
        ("Demos", "/demos", "eight, each a real call against production"),
        ("Walk a world", "/worlds", "signed terrain you can fly through"),
        ("The channel", "/channel", "agents talking, every message signed"),
        ("Scoreboard", "/scoreboard", "the live benchmark, two heats"),
        ("Gallery", "/gallery", "what the record looks like rendered"),
    ]),
    ("Verify", [
        ("Check a receipt", "/verify", "paste any token, the proof runs in your browser"),
        ("emem-guard", "/guard", "allow or deny, signed, with a reason"),
        ("Transparency log", "/v1/log/sth", "pin a signed head, prove it only ever grew"),
        ("Who writes here", "/agents", "every attester, discovered not curated"),
    ]),
    ("Build", [
        ("Reference", "/reference", "the read surface, endpoint by endpoint"),
        ("OpenAPI", "/openapi.json", "the machine contract"),
        ("Skills", "/skills.md", "runnable procedures for an agent"),
        ("Clients", "/clients", "connect Claude, Cursor, or your own"),
        ("A2A", "/a2a", "how two agents share one memory"),
        ("Docs", "/docs", "the book"),
    ]),
]

GITHUB = "https://github.com/Vortx-AI/emem"


def render(current: str) -> str:
    """`current` is the path of the page being rendered, for the on state."""
    out = [START, '<header class="sitebar"><nav class="sitebar-in" aria-label="Site">',
           '<a href="/" class="brand"><img src="/vortxgola.gif" alt="">emem</a>']
    for group, items in NAV:
        hit = any(h == current for _, h, _ in items)
        out.append(f'<details class="navgrp{" on" if hit else ""}">')
        out.append(f'<summary>{group}</summary>')
        out.append('<div class="navmenu">')
        for label, href, note in items:
            mark = ' aria-current="page"' if href == current else ''
            out.append(f'<a href="{href}"{mark}><b>{label}</b><span>{note}</span></a>')
        out.append('</div></details>')
    out.append('<span class="sitebar-gap"></span>')
    out.append('<a class="navplain" href="/mcp">MCP</a>')
    out.append(f'<a class="navplain" href="{GITHUB}" rel="noopener">GitHub</a>')
    out.append('</nav></header>')
    out.append(END)
    return "\n".join(out)


# The nav a page carries today, in any of its seven shapes.
OLD = re.compile(r'<header class="statusbar">.*?</header>', re.S)
GEN = re.compile(re.escape(START) + r'.*?' + re.escape(END), re.S)

# Which path each file is served at, for the current-page state.
def served_as(name: str) -> str:
    if name == "index.html":
        return "/"
    if name.startswith("demos-") and name != "demos-index.html":
        return "/demos/" + name[len("demos-"):-len(".html")]
    return "/" + name[:-len(".html")]


SKIP = {"channel.html": "generated by build_channel.py, which owns its markup",
        "card.html": "a fixed-size share card with no site chrome",
        "api-redoc.html": "hosts a third-party renderer with its own frame"}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    changed, drifted, skipped = [], [], []
    for path in sorted(glob.glob("web/*.html")):
        name = os.path.basename(path)
        if name in SKIP:
            skipped.append(name)
            continue
        s = open(path, encoding="utf-8").read()
        nav = render(served_as(name))
        if GEN.search(s):
            out = GEN.sub(lambda _: nav, s, count=1)
        elif OLD.search(s):
            out = OLD.sub(lambda _: nav, s, count=1)
        else:
            # /tools and /scoreboard were built as bare pages with no site
            # chrome at all, so there is nothing to replace and the nav is
            # inserted instead. A reader who lands on either had no way back
            # except the browser button.
            # /scoreboard has no <body> tag at all: it is a fragment and the
            # browser implies one. Fall back to the first content element.
            m = re.search(r'<body[^>]*>', s)
            if m:
                out = s[:m.end()] + "\n" + nav + s[m.end():]
            else:
                m = re.search(r'\n<(?:main|section|div|header)[ >]', s)
                if not m:
                    drifted.append(f"{name}: nowhere to insert a nav")
                    continue
                out = s[:m.start()] + "\n" + nav + s[m.start():]
        if "/nav.css" not in out:
            out = out.replace('<link rel=stylesheet href="/tokens.css">',
                              '<link rel=stylesheet href="/tokens.css">\n'
                              '<link rel=stylesheet href="/nav.css">', 1)
        if out != s:
            if a.check:
                drifted.append(f"{name}: nav does not match scripts/gen_nav.py")
            else:
                open(path, "w", encoding="utf-8").write(out)
                changed.append(name)

    total = sum(len(i) for _, i in NAV) + 2
    print(f"nav: {len(NAV)} groups, {total} destinations, "
          f"{len(skipped)} pages skipped ({', '.join(sorted(skipped))})")
    if a.check:
        if drifted:
            print("\nA nav that is edited per page becomes seven navs. It did.")
            for d in drifted:
                print(f"  {d}")
            return 1
        print("Every page carries the generated nav.")
        return 0
    print(f"rewrote {len(changed)} pages")
    for d in drifted:
        print(f"  ! {d}")
    return 1 if drifted else 0


if __name__ == "__main__":
    sys.exit(main())
