#!/usr/bin/env python3
"""Every provenance_class we emit must be one we declare.

Why this is a gate and not a fix
--------------------------------
The upstream found an undeclared class, `measurement`, on eleven of their
surfaces -- more often than one of the real ones appeared. The correct diagnosis
was already written down in their own tree, in full, under a heading explaining
why that word was wrong. It had reached exactly one call site.

Ours was `rendering_of_measurement`, on the ground-postcard descriptor in the
ask payload. A hybrid name implies a hybrid guarantee, and there is none: a
drawing does not recompute and carries no hash. It is retired for `none`, which
is a statement that the thing sits outside the provenance system rather than an
eighth class.

That fix, on its own, is the fix that already failed once for both of us. So the
rule is checked rather than remembered.

What counts as declared
-----------------------
The seven in `emem_core::substrates::KNOWN_PROVENANCE`, plus `none`, which is
admitted EXPLICITLY as an out-of-system declaration and not as a class. A value
outside that set is either a typo or a new guarantee nobody has defined, and
both should stop a build.
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SUBSTRATES = REPO / "crates" / "emem-core" / "src" / "substrates.rs"
CRATE_ROOT = REPO / "crates"


def declared() -> set[str]:
    """Read the canonical list out of the source, never a copy of it.

    And the two sides of every comparison here come from DIFFERENT places, which
    is a stronger property than not carrying a copy. The upstream built a gate
    whose two sides both came from one variable -- a document compared to the
    list it is generated by iterating -- so a ghost entry passed and the check
    could not fail. A green line asserting a property it never tests is worse
    than no line, because it retires the question.

    Checked here: `substrates.rs` holds KNOWN_PROVENANCE and contains zero
    `"provenance_class": "..."` literals and zero enum lists, so the canon file
    is never on both sides. The emitted values and the published vocabularies
    live in other crates entirely, and either can disagree with this list.
    """
    src = SUBSTRATES.read_text(encoding="utf-8")
    m = re.search(r"const KNOWN_PROVENANCE:\s*\[&str;\s*\d+\]\s*=\s*\[(.*?)\];", src, re.S)
    if not m:
        sys.exit("could not find KNOWN_PROVENANCE in substrates.rs; "
                 "this gate reads the list rather than restating it, so it "
                 "cannot run if the list moves")
    return set(re.findall(r'"([a-z_]+)"', m.group(1)))


# Provenance enums that are deliberately NOT the whole vocabulary, keyed by
# their sorted contents, with the reason each is a subset. A subset not in this
# table fails: writing the reason down is the price of publishing a partial
# vocabulary, because a partial vocabulary teaches a filter to drop things.
DELIBERATE_SUBSETS: dict[tuple[str, ...], str] = {
    ("human_curated", "model_output"): (
        "attest input: direct_sensor and deterministic_index are REFUSED as a "
        "declaration -- this responder did not compute your value and will not "
        "take your word that it is recomputable. It can still EARN "
        "deterministic_index by re-running a pure op over the cited parents."
    ),
    ("estimator", "human_curated", "model_output"): (
        "attest input, wider form: the three an external attester may declare "
        "about its own value. Same refusal as above for the recomputable pair."
    ),
}


def enum_vocabularies(allowed: set[str]) -> list[str]:
    """Every published provenance enum must be the whole vocabulary or a declared subset."""
    import json as _json

    problems: list[str] = []
    seen = 0
    for f in sorted(CRATE_ROOT.glob("**/*.rs")):
        text = f.read_text(encoding="utf-8", errors="ignore")
        for m in re.finditer(r'"enum"\s*:\s*\[([^\]]*)\]', text):
            vals = set(re.findall(r'"([a-z_]+)"', m.group(1)))
            # Only lists that are unmistakably this vocabulary.
            if not vals & {"direct_sensor", "model_output", "human_curated"}:
                continue
            if vals - allowed:
                continue  # a different vocabulary that happens to share a word
            seen += 1
            if vals == allowed:
                continue
            key = tuple(sorted(vals))
            if key in DELIBERATE_SUBSETS:
                continue
            line = text[: m.start()].count("\n") + 1
            try:
                rel = str(f.relative_to(REPO))
            except ValueError:
                rel = str(f)
            problems.append(
                f"!! {rel}:{line}: publishes {len(vals)} of {len(allowed)} classes, "
                f"missing {sorted(allowed - vals)}. Complete it, or add it to "
                f"DELIBERATE_SUBSETS with the reason it is partial."
            )
    if not seen:
        # Same vacuous-truth rule as the literal scan: no enums found means the
        # schema moved, not that every vocabulary is complete.
        problems.append(
            "!! found NO published provenance enums at all: the schema shape "
            "moved, or the root is wrong. This half of the gate is measuring "
            "nothing rather than passing."
        )
    elif not problems:
        print(f"  {seen} published provenance enum(s): complete or declared subsets")
    return problems


def main(argv: list[str] | None = None) -> int:
    # An optional root, so this gate can be run against a FIXTURE containing the
    # case and nothing else.
    #
    # The upstream showed today why that matters: they controlled a keyword gate
    # by reintroducing the bad string into their real tree, it passed, and it
    # passed for a reason unrelated to the property -- the surrounding sentence
    # happened to contain a word the checker was looking for. A control run
    # against a real codebase can succeed by accident. A control run against two
    # files, one of each kind and nothing else in them, cannot.
    argv = sys.argv[1:] if argv is None else argv
    global CRATE_ROOT
    if argv:
        CRATE_ROOT = Path(argv[0])

    allowed = declared()
    # `none` is not a class. It is the statement that the thing being described
    # is outside the provenance system, and it is admitted so that saying so
    # stays possible without minting a class to say it with.
    admitted = allowed | {"none"}

    # Every literal assigned to a provenance_class field, in Rust or in JSON.
    pat = re.compile(r'"provenance_class"\s*:\s*"([^"]+)"')
    bad: list[tuple[str, int, str]] = []
    seen: dict[str, int] = {}
    for f in sorted(CRATE_ROOT.glob("**/*.rs")):
        text = f.read_text(encoding="utf-8", errors="ignore")
        for m in pat.finditer(text):
            val = m.group(1)
            seen[val] = seen.get(val, 0) + 1
            if val not in admitted:
                line = text[: m.start()].count("\n") + 1
                try:
                    rel = str(f.relative_to(REPO))
                except ValueError:
                    rel = str(f)
                bad.append((rel, line, val))

    print(f"provenance classes: {len(allowed)} declared, "
          f"{len(seen)} distinct emitted, {sum(seen.values())} sites")
    for val, n in sorted(seen.items(), key=lambda kv: -kv[1]):
        mark = "" if val in admitted else "   <-- NOT DECLARED"
        note = "  (out-of-system statement, not a class)" if val == "none" else ""
        print(f"  {val:26} {n:3}{note}{mark}")

    # THE VOCABULARY WE TEACH, not just the values we emit.
    #
    # The upstream noticed that a filter written against a SHORTER class list
    # silently drops facts carrying the classes it does not name. Ours had that
    # exactly: the MCP recall filter's enum listed six of the seven, omitting
    # `estimator`, so an agent enumerating the enum to mean "everything" would
    # build a filter that excludes a class the day a band uses it. Latent today
    # (no estimator band exists) and invisible when it stops being latent,
    # because the responder accepts the value -- the enum is a description, not
    # an enforcement, so nothing errors.
    #
    # Subsets are sometimes correct: the attest input deliberately refuses
    # `direct_sensor` and `deterministic_index` because this responder will not
    # take an attester's word that a value is recomputable. A subset must
    # therefore be DECLARED, with its reason, rather than merely tolerated.
    subset_problems = enum_vocabularies(allowed)
    for line in subset_problems:
        print(f"  {line}")

    # A GATE THAT MATCHED NOTHING MUST NOT REPORT GREEN.
    #
    # The upstream noticed this property in openapi_coverage -- which refuses to
    # pass when it parses zero routes or zero descriptions -- and said they had
    # not put it anywhere. Neither had I, in the gate I wrote today: pointed at
    # a tree with no provenance in it, it printed "0 sites" and then "Every
    # emitted provenance class is one we declare", which is TRUE and useless.
    #
    # Rename the field, change the JSON shape, move the crates, and this becomes
    # a green line asserting a property it no longer tests. Vacuous truth is the
    # same failure as one copy compared to itself, reached by a different road:
    # in both cases the check cannot fail, and in both cases its passing looks
    # exactly like the thing working.
    if not seen:
        print("\nMATCHED NOTHING. This gate looks for `\"provenance_class\": \"...\"`")
        print("and found none anywhere under the scanned root. Either the field")
        print("was renamed, the shape changed, or the root is wrong -- and any of")
        print("those means this gate is measuring nothing rather than passing.")
        return 1

    if bad or subset_problems:
        if not bad:
            print("\nAn undeclared provenance SUBSET is published as a vocabulary.")
            return 1
        print("\nUNDECLARED PROVENANCE CLASS EMITTED:")
        for rel, line, val in bad:
            print(f"  {rel}:{line}: {val!r}")
        print("\nA class outside the declared set is either a typo or a guarantee")
        print("nobody has defined. If the thing genuinely has no provenance, say")
        print("`none` and name what does carry it; do not mint a hybrid name,")
        print("because a hybrid name implies a hybrid guarantee.")
        return 1

    print("\nEvery emitted provenance class is one we declare.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
