#!/usr/bin/env python3
"""Do the bytes a visitor receives match the bytes in this tree?

    python3 scripts/served_matches_tree.py
    python3 scripts/served_matches_tree.py --origin http://127.0.0.1:5051

Why this is not deploy_drift.py
-------------------------------
`deploy_drift.py` compares the responder's SELF-REPORTED commit to HEAD. That is
a claim about provenance and it is worth checking, but it is a claim: the binary
says which commit it thinks it came from. Two states get past it.

A binary built from a working tree that was ahead of HEAD reports the older sha
and serves the newer bytes. That happened here on 2026-08-24, because a commit
landed while cargo was mid-build, and the attestation named a commit that did
not contain what was running.

The commoner one is simpler and cost more today: the fix was committed, the tree
was right, every gate passed, and the binary had not been rebuilt yet. Nothing
in this repository could see that, because every gate reads the tree. It took an
agent on the other side of the socket fetching the page and finding the CSS rule
absent from the served bytes.

So this compares CONTENT, not a recorded sha. It fetches the pages the binary
bakes with `include_str!` and diffs them against the files on disk. A mismatch
means the deploy has not taken, whatever the stamp says, and it says which page
and by how much.

What it does not claim
----------------------
That the tree is correct. Only that what is being served is what is here. A page
generated at deploy time (`web/channel.html`, `web/tools.html`,
`web/whitepaper-v2.html`) is REGENERATED after this tree's copy was written, so
it is expected to differ and is listed with that reason rather than silently
skipped.
"""
import argparse
import re
import difflib
import hashlib
import pathlib
import sys
import urllib.error
import urllib.request

REPO = pathlib.Path(__file__).resolve().parent.parent

# (served path, file in web/). Only pages baked verbatim by include_str!.
PAGES = [
    ("/", "index.html"),
    ("/verify", "verify.html"),
    ("/how-it-works", "how-it-works.html"),
    ("/solutions", "solutions.html"),
    ("/reference", "reference.html"),
    ("/a2a", "a2a.html"),
    ("/guard", "guard.html"),
    ("/gallery", "gallery.html"),
    ("/worlds", "worlds.html"),
    ("/agents", "agents.html"),
    ("/demos", "demos-index.html"),
    ("/scoreboard", "scoreboard.html"),
    ("/tokens.css", "tokens.css"),
    ("/nav.css", "nav.css"),
]

# Regenerated by redeploy.sh AFTER this tree's copy was written, so a difference
# is the pipeline working rather than a stale binary. Named with the reason, not
# silently skipped.
REGENERATED = {
    "channel.html": "build_channel.py rewrites it every deploy",
    "tools.html": "gen_tools_page.py rewrites it every deploy",
    "whitepaper-v2.html": "render_whitepaper.py rewrites it every deploy",
}


def fetch(url: str):
    req = urllib.request.Request(url, headers={
        "user-agent": "emem-served-matches-tree",
        "accept": "text/html,text/css,*/*",
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            return r.read(), None
    except urllib.error.HTTPError as e:
        return None, f"HTTP {e.code}"
    except Exception as e:
        return None, str(e)[:90]


def first_difference(a: str, b: str) -> str:
    """The first line that differs, so the report names something actionable."""
    for line in difflib.unified_diff(a.split("\n"), b.split("\n"), n=0, lineterm=""):
        if line.startswith(("+++", "---", "@@")):
            continue
        return " ".join(line.split())[:120]
    return "(identical line-wise; the difference is whitespace or encoding)"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--origin", default="https://emem.dev")
    args = ap.parse_args()

    # Pages the responder SUBSTITUTES INTO before serving. A byte comparison is
    # wrong for these by construction, and my first run said so: `/` came back
    # 408 bytes LARGER than the file, with the first difference at
    # `<!--##ALBUM_FIRST##-->`, which lib.rs replaces with the rendered album at
    # request time. The tool manufactured a fault one turn after I wrote a note
    # about tools manufacturing faults.
    #
    # Handled by splitting the file at the placeholder and requiring the served
    # bytes to open with the prefix and close with the suffix. That still catches
    # a stale binary -- the prefix contains the whole head and most of the body --
    # without asserting anything about the part that is meant to differ.
    # Empty since 2026-08-26, and that is a STRENGTHENING: the homepage carried
    # `<!--##ALBUM_FIRST##-->` while lib.rs rendered the album into it at request
    # time, so a byte comparison was wrong for that one page by construction.
    # `rendered_index_html()` is now a pass-through and the album is gone, so `/`
    # falls through to the same sha256 comparison every other page gets. Add a
    # row here only for a page the responder genuinely substitutes into, and note
    # that a row whose marker is missing from the file is reported as drift
    # rather than skipped, which is how this one announced itself.
    TEMPLATED = {}

    # THE SECOND DEPLOY PATH, which this file did not watch.
    #
    # web/*.html is baked into the binary, so a stale binary shows up above. The
    # /docs tree is NOT: mdBook rebuilds it separately, into its own artifact,
    # with its own fingerprinted filenames. That path can be a full revert behind
    # while every check here is green, and it just was: a padding fix landed in
    # the tree, the binary picked it up, and the docs kept serving the previous
    # theme because the mdBook build had already run earlier in the same deploy.
    # Nothing inside this repository noticed. A neighbouring responder measuring
    # the live pages did.
    #
    # The served theme is byte-identical to docs/theme/emem.css, so the check is
    # the same one as above: follow the fingerprinted href a docs page actually
    # links, fetch it, compare.
    def check_docs_theme():
        page, err = fetch(f"{args.origin}/docs/protocol.html")
        if page is None:
            return ("unreachable", f"/docs/protocol.html did not answer: {err}")
        m = re.search(rb'href="(theme/emem-[a-f0-9]+\.css)"', page)
        if not m:
            return ("drift", "no fingerprinted theme href on /docs/protocol.html; "
                             "mdBook's output shape changed and this check is now blind")
        href = m.group(1).decode()
        served, err = fetch(f"{args.origin}/docs/{href}")
        if served is None:
            return ("unreachable", f"/docs/{href} did not answer: {err}")
        disk = (REPO / "docs" / "theme" / "emem.css").read_bytes()
        if served == disk:
            return ("ok", href)
        return ("drift", f"/docs/{href} differs from docs/theme/emem.css at "
                         f"{first_difference(disk.decode('utf-8', 'replace'), served.decode('utf-8', 'replace'))}; "
                         f"the mdBook tree was not rebuilt from this theme")

    checked, drifted, unreachable = 0, [], 0
    verdict, detail = check_docs_theme()
    if verdict == "drift":
        drifted.append(("/docs/*", "docs/theme/emem.css", detail))
    elif verdict == "unreachable":
        unreachable += 1
    else:
        checked += 1

    for path, name in PAGES:
        disk = REPO / "web" / name
        if not disk.exists():
            drifted.append((path, name, f"{name} is not in web/ at all"))
            continue
        body, err = fetch(args.origin.rstrip("/") + path)
        if body is None:
            unreachable += 1
            continue
        checked += 1
        if name in TEMPLATED:
            marker = TEMPLATED[name]
            text = disk.read_text(encoding="utf-8", errors="replace")
            got = body.decode("utf-8", "replace")
            if marker not in text:
                drifted.append((path, name, f"expected the template marker {marker} "
                                            f"in web/{name} and it is not there, so this "
                                            f"page is no longer templated the way this "
                                            f"check assumes"))
                continue
            head, _, tail = text.partition(marker)
            if not got.startswith(head) or not got.endswith(tail):
                where = "before" if not got.startswith(head) else "after"
                drifted.append((path, name, f"the served page diverges {where} the "
                                            f"templated block; {len(body)}b served vs "
                                            f"{disk.stat().st_size}b on disk"))
            continue

        served = hashlib.sha256(body).hexdigest()
        local = hashlib.sha256(disk.read_bytes()).hexdigest()
        if served != local:
            where = first_difference(
                disk.read_text(encoding="utf-8", errors="replace"),
                body.decode("utf-8", "replace"),
            )
            drifted.append((path, name, f"{len(body)}b served vs {disk.stat().st_size}b on "
                                        f"disk; first difference: {where}"))

    # Reaching nothing is not agreement.
    if checked == 0:
        print(f"  {args.origin} served none of {len(PAGES)} pages. Undetermined, "
              f"not matching: this check has to receive bytes to compare them.")
        return 1

    print(f"served vs tree: {checked} page(s) compared against {args.origin}"
          + (f", {unreachable} unreachable" if unreachable else ""))
    print(f"  ({len(REGENERATED)} generated pages are not compared: "
          + "; ".join(f"{k} -- {v}" for k, v in REGENERATED.items()) + ")")
    if drifted:
        print("\nTHE BYTES BEING SERVED ARE NOT THE BYTES IN THIS TREE:")
        for path, name, why in drifted:
            print(f"  {path} (web/{name}): {why}")
        print("\nThe usual cause is the simplest one: the tree is right, the gates")
        print("pass, and the binary has not been rebuilt. web/*.html is baked in")
        print("by include_str!, so an edit is not deployed until cargo has run and")
        print("the unit has restarted.")
        return 1
    print("Every page a visitor receives is byte-identical to the file in this tree.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
